/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_applifier_impact_android_ndk_AndroidNativeBridge */

#ifndef _Included_com_applifier_impact_android_ndk_AndroidNativeBridge
#define _Included_com_applifier_impact_android_ndk_AndroidNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_applifier_impact_android_ndk_AndroidNativeBridge
 * Method:    bridgeReady
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_applifier_impact_android_ndk_AndroidNativeBridge_bridgeReady
  (JNIEnv *, jobject);

/*
 * Class:     com_applifier_impact_android_ndk_AndroidNativeBridge
 * Method:    dispatchEvent
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_applifier_impact_android_ndk_AndroidNativeBridge_dispatchEvent
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_applifier_impact_android_ndk_AndroidNativeBridge
 * Method:    setRewardItems
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_applifier_impact_android_ndk_AndroidNativeBridge_setRewardItems
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
